#!/bin/bash

cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/camera_config.xml proprietary/vendor/etc/camera/camera_config.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/csidtg_camera.xml proprietary/vendor/etc/camera/csidtg_camera.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/csidtg_chromatix.xml proprietary/vendor/etc/camera/csidtg_chromatix.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/lf_facerank_model.bin proprietary/vendor/etc/camera/lf_facerank_model.bin
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/ov13855_chromatix.xml proprietary/vendor/etc/camera/ov13855_chromatix.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/ov13855_f13v10l_chromatix.xml proprietary/vendor/etc/camera/ov13855_f13v10l_chromatix.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/s5k3p8sp_chromatix.xml proprietary/vendor/etc/camera/s5k3p8sp_chromatix.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/s5k5e8_chromatix.xml proprietary/vendor/etc/camera/s5k5e8_chromatix.xml
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin proprietary/vendor/etc/camera/sdm_ys_32p_120_21_5_perturb50.bin
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libarcsoft_high_dynamic_range.so proprietary/vendor/lib/libarcsoft_high_dynamic_range.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libdepthmapwrapper.so proprietary/vendor/lib/libdepthmapwrapper.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libdualcameraddm.so proprietary/vendor/lib/libdualcameraddm.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libflash_pmic.so proprietary/vendor/lib/libflash_pmic.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libjpegdhw.so proprietary/vendor/lib/libjpegdhw.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libjpegdmahw.so proprietary/vendor/lib/libjpegdmahw.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libjpegehw.so proprietary/vendor/lib/libjpegehw.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmlib2d_interface.so proprietary/vendor/lib/libmmlib2d_interface.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_dbg.so proprietary/vendor/lib/libmmcamera_dbg.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_dummyalgo.so proprietary/vendor/lib/libmmcamera_dummyalgo.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_eebinparse.so proprietary/vendor/lib/libmmcamera_eebinparse.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_eeprom_util.so proprietary/vendor/lib/libmmcamera_eeprom_util.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_eztune_module.so proprietary/vendor/lib/libmmcamera_eztune_module.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_facedetection_lib.so proprietary/vendor/lib/libmmcamera_facedetection_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_faceproc.so proprietary/vendor/lib/libmmcamera_faceproc.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_faceproc2.so proprietary/vendor/lib/libmmcamera_faceproc2.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_hvx_add_constant.so proprietary/vendor/lib/libmmcamera_hvx_add_constant.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_hvx_grid_sum.so proprietary/vendor/lib/libmmcamera_hvx_grid_sum.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_imglib.so proprietary/vendor/lib/libmmcamera_imglib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so proprietary/vendor/lib/libmmcamera_imglib_faceproc_adspstub.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_paaf_lib.so proprietary/vendor/lib/libmmcamera_paaf_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_pdaf.so proprietary/vendor/lib/libmmcamera_pdaf.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_pdafcamif.so proprietary/vendor/lib/libmmcamera_pdafcamif.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_ppbase_module.so proprietary/vendor/lib/libmmcamera_ppbase_module.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_ppeiscore.so proprietary/vendor/lib/libmmcamera_ppeiscore.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_quadracfa.so proprietary/vendor/lib/libmmcamera_quadracfa.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_sw2d_lib.so proprietary/vendor/lib/libmmcamera_sw2d_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_thread_services.so proprietary/vendor/lib/libmmcamera_thread_services.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_tintless_algo.so proprietary/vendor/lib/libmmcamera_tintless_algo.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_tuning_lookup.so proprietary/vendor/lib/libmmcamera_tuning_lookup.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_tuning.so proprietary/vendor/lib/libmmcamera_tuning.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_c2d_module.so proprietary/vendor/lib/libmmcamera2_c2d_module.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_cpp_module.so proprietary/vendor/lib/libmmcamera2_cpp_module.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so proprietary/vendor/lib/libmmcamera2_frame_algorithm.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_iface_modules.so proprietary/vendor/lib/libmmcamera2_iface_modules.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_imglib_modules.so proprietary/vendor/lib/libmmcamera2_imglib_modules.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_is.so proprietary/vendor/lib/libmmcamera2_is.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_isp_modules.so proprietary/vendor/lib/libmmcamera2_isp_modules.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_mct_shimlayer.so proprietary/vendor/lib/libmmcamera2_mct_shimlayer.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_mct.so proprietary/vendor/lib/libmmcamera2_mct.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so proprietary/vendor/lib/libmmcamera2_pp_buf_mgr.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_pproc_modules.so proprietary/vendor/lib/libmmcamera2_pproc_modules.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_q3a_core.so proprietary/vendor/lib/libmmcamera2_q3a_core.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_sensor_modules.so proprietary/vendor/lib/libmmcamera2_sensor_modules.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so proprietary/vendor/lib/libmmcamera2_stats_algorithm.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_stats_lib.so proprietary/vendor/lib/libmmcamera2_stats_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera2_stats_modules.so proprietary/vendor/lib/libmmcamera2_stats_modules.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmjpeg.so proprietary/vendor/lib/libmmjpeg.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmqjpeg_codec.so proprietary/vendor/lib/libmmqjpeg_codec.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmqjpegdma.so proprietary/vendor/lib/libmmqjpegdma.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmpbase.so proprietary/vendor/lib/libmpbase.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libqomx_jpegdec.so proprietary/vendor/lib/libqomx_jpegdec.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libqomx_jpegenc_pipe.so proprietary/vendor/lib/libqomx_jpegenc_pipe.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libqomx_jpegenc.so proprietary/vendor/lib/libqomx_jpegenc.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libremosaic_daemon.so proprietary/vendor/lib/libremosaic_daemon.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscveBlobDescriptor.so proprietary/vendor/lib/libscveBlobDescriptor.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscveBlobDescriptor_stub.so proprietary/vendor/lib/libscveBlobDescriptor_stub.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscveFaceLandmarks.so proprietary/vendor/lib/libscveFaceLandmarks.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscveFaceLandmarks_stub.so proprietary/vendor/lib/libscveFaceLandmarks_stub.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscveFaceRecognition.so proprietary/vendor/lib/libscveFaceRecognition.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscveImageCorrection.so proprietary/vendor/lib/libscveImageCorrection.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscvePanorama.so proprietary/vendor/lib/libscvePanorama.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libscvePanorama_lite.so proprietary/vendor/lib/libscvePanorama_lite.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libts_face_beautify_hal.so proprietary/vendor/lib/libts_face_beautify_hal.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libts_detected_face_hal.so proprietary/vendor/lib/libts_detected_face_hal.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libvideobokeh.so proprietary/vendor/lib/libvideobokeh.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libvideoutils.so proprietary/vendor/lib/libvideoutils.so


cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libactuator_bu64297_f13v10l.so proprietary/vendor/lib/libactuator_bu64297_f13v10l.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so proprietary/vendor/lib/libactuator_rohm_bu64243gwz.so


cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_csidtg_common.so proprietary/vendor/lib/libchromatix_csidtg_common.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_csidtg_cpp_preview.so proprietary/vendor/lib/libchromatix_csidtg_cpp_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_csidtg_postproc.so proprietary/vendor/lib/libchromatix_csidtg_postproc.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_csidtg_preview.so proprietary/vendor/lib/libchromatix_csidtg_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_csidtg_zsl_preview.so proprietary/vendor/lib/libchromatix_csidtg_zsl_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_zsl_video_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_zsl_video_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_ds_chromatix_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_ds_chromatix_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_ds_chromatix_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_ds_chromatix_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_hht_120.so proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_hht_120.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_hht_60.so proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_hht_60.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_hht_90.so proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_hht_90.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_liveshot_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_liveshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_zsl_preview_bu64297_d9.so proprietary/vendor/lib/libchromatix_ov13855_zsl_preview_bu64297_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_zsl_preview_bu64297_video_call.so proprietary/vendor/lib/libchromatix_ov13855_zsl_preview_bu64297_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_zsl_video_bu64297_d9.so proprietary/vendor/lib/libchromatix_ov13855_zsl_video_bu64297_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_preview_bu64297_video_call.so proprietary/vendor/lib/libchromatix_ov13855_default_preview_bu64297_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_ds_chromatix.so proprietary/vendor/lib/libchromatix_ov13855_cpp_ds_chromatix.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_ov13855_f13v10l.so proprietary/vendor/lib/libmmcamera_ov13855_f13v10l.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_hfr_120_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_hfr_120_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_video_bu64297_video_call.so proprietary/vendor/lib/libchromatix_ov13855_default_video_bu64297_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_hfr_120.so proprietary/vendor/lib/libchromatix_ov13855_hfr_120.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_zsl_preview_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_zsl_preview_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_video_video_call.so proprietary/vendor/lib/libchromatix_ov13855_default_video_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_qtech_ov13855_eeprom.so proprietary/vendor/lib/libmmcamera_qtech_ov13855_eeprom.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_video_full.so proprietary/vendor/lib/libchromatix_ov13855_cpp_video_full.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_video_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_video_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_video_full_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_video_full_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_60.so proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_60.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_hfr_90.so proprietary/vendor/lib/libchromatix_ov13855_hfr_90.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_snapshot.so proprietary/vendor/lib/libchromatix_ov13855_snapshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_90.so proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_90.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_preview.so proprietary/vendor/lib/libchromatix_ov13855_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_preview_d9.so proprietary/vendor/lib/libchromatix_ov13855_preview_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_us_chromatix_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_us_chromatix_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_zsl_video_bu64297_video_call.so proprietary/vendor/lib/libchromatix_ov13855_zsl_video_bu64297_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_preview.so proprietary/vendor/lib/libchromatix_ov13855_cpp_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_preview_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_preview_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_hfr_90_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_hfr_90_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_video.so proprietary/vendor/lib/libchromatix_ov13855_default_video.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_video_d9.so proprietary/vendor/lib/libchromatix_ov13855_default_video_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_hfr_60_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_hfr_60_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_preview_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_default_preview_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_preview_bu64297_d9.so proprietary/vendor/lib/libchromatix_ov13855_default_preview_bu64297_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_liveshot_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_liveshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_video.so proprietary/vendor/lib/libchromatix_ov13855_cpp_video.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_120.so proprietary/vendor/lib/libchromatix_ov13855_cpp_hfr_120.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_postproc.so proprietary/vendor/lib/libchromatix_ov13855_postproc.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_common.so proprietary/vendor/lib/libchromatix_ov13855_common.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_video_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_video_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_hfr_60.so proprietary/vendor/lib/libchromatix_ov13855_hfr_60.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_video_full_video_call.so proprietary/vendor/lib/libchromatix_ov13855_video_full_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_us_chromatix.so proprietary/vendor/lib/libchromatix_ov13855_cpp_us_chromatix.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_preview_video_call.so proprietary/vendor/lib/libchromatix_ov13855_preview_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_preview_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_preview_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot.so proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_hht.so proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_hht.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_video_full.so proprietary/vendor/lib/libchromatix_ov13855_video_full.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_video_full_d9.so proprietary/vendor/lib/libchromatix_ov13855_video_full_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_video_full_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_video_full_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_snapshot_d9.so proprietary/vendor/lib/libchromatix_ov13855_snapshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_snapshot_video_call.so proprietary/vendor/lib/libchromatix_ov13855_snapshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_liveshot.so proprietary/vendor/lib/libchromatix_ov13855_cpp_liveshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_video_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_video_hht_call.so proprietary/vendor/lib/libchromatix_ov13855_cpp_snapshot_video_hht_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_cpp_us_chromatix_d9.so proprietary/vendor/lib/libchromatix_ov13855_cpp_us_chromatix_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_video_bu64297.so proprietary/vendor/lib/libchromatix_ov13855_default_video_bu64297.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_default_video_bu64297_d9.so proprietary/vendor/lib/libchromatix_ov13855_default_video_bu64297_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_liveshot.so proprietary/vendor/lib/libchromatix_ov13855_liveshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_liveshot_d9.so proprietary/vendor/lib/libchromatix_ov13855_liveshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_ov13855_liveshot_video_call.so proprietary/vendor/lib/libchromatix_ov13855_liveshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_preview_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_preview_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_video.so proprietary/vendor/lib/libchromatix_s5k5e8_video.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_preview_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_preview_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_video.so proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_video.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_video_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_video_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_postproc.so proprietary/vendor/lib/libchromatix_s5k5e8_postproc.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_liveshot_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_liveshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_preview_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_preview_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_preview.so proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_preview.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_preview_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_preview_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_video_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_video_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot.so proprietary/vendor/lib/libchromatix_s5k5e8_snapshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_s5k5e8.so proprietary/vendor/lib/libmmcamera_s5k5e8.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_common.so proprietary/vendor/lib/libchromatix_s5k5e8_common.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_common_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_common_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_video.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_video.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_liveshot.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_liveshot.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_liveshot_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_liveshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_qtech_s5k5e8_eeprom.so proprietary/vendor/lib/libmmcamera_qtech_s5k5e8_eeprom.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_video_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_video_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m_video_hht_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m_video_hht_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_hht.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_hht.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_video_hht_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_video_hht_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_video_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_video_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_postproc_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_postproc_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_preview_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_preview_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_snapshot_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_video_d9.so proprietary/vendor/lib/libchromatix_s5k5e8_video_d9.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_preview.so proprietary/vendor/lib/libchromatix_s5k5e8_preview.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_video_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_a3_zsl_video_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_preview_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_preview_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_snapshot_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_snapshot_video_call.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m_video_call.so proprietary/vendor/lib/libchromatix_s5k5e8_cpp_snapshot_4m_video_call.so


cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw


cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libois_bu63165.so proprietary/vendor/lib/libois_bu63165.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libois_lc898122.so proprietary/vendor/lib/libois_lc898122.so


cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libchromaflash.so proprietary/vendor/lib/libchromaflash.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libllvd_smore.so proprietary/vendor/lib/libllvd_smore.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_bokeh.so proprietary/vendor/lib/libmmcamera_bokeh.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_chromaflash_lib.so proprietary/vendor/lib/libmmcamera_chromaflash_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_csidtg.so proprietary/vendor/lib/libmmcamera_csidtg.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_depth_map.so proprietary/vendor/lib/libmmcamera_depth_map.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_dw9761b_2d_eeprom.so proprietary/vendor/lib/libmmcamera_dw9761b_2d_eeprom.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_abf48.so proprietary/vendor/lib/libmmcamera_isp_abf48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_aec_bg_stats47.so proprietary/vendor/lib/libmmcamera_isp_aec_bg_stats47.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so proprietary/vendor/lib/libmmcamera_isp_bf_stats47.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_bg_stats46.so proprietary/vendor/lib/libmmcamera_isp_bg_stats46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so proprietary/vendor/lib/libmmcamera_isp_bhist_stats44.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_black_level48.so proprietary/vendor/lib/libmmcamera_isp_black_level48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_bpc48.so proprietary/vendor/lib/libmmcamera_isp_bpc48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_cac47.so proprietary/vendor/lib/libmmcamera_isp_cac47.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so proprietary/vendor/lib/libmmcamera_isp_chroma_enhan40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so proprietary/vendor/lib/libmmcamera_isp_chroma_suppress40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so proprietary/vendor/lib/libmmcamera_isp_clamp_encoder40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so proprietary/vendor/lib/libmmcamera_isp_clamp_video40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so proprietary/vendor/lib/libmmcamera_isp_clamp_viewfinder40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_color_correct46.so proprietary/vendor/lib/libmmcamera_isp_color_correct46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder46.so proprietary/vendor/lib/libmmcamera_isp_color_xform_encoder46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_color_xform_video46.so proprietary/vendor/lib/libmmcamera_isp_color_xform_video46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so proprietary/vendor/lib/libmmcamera_isp_color_xform_viewfinder46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_cs_stats46.so proprietary/vendor/lib/libmmcamera_isp_cs_stats46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_demosaic48.so proprietary/vendor/lib/libmmcamera_isp_demosaic48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_demux48.so proprietary/vendor/lib/libmmcamera_isp_demux48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so proprietary/vendor/lib/libmmcamera_isp_fovcrop_encoder46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_fovcrop_video46.so proprietary/vendor/lib/libmmcamera_isp_fovcrop_video46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so proprietary/vendor/lib/libmmcamera_isp_fovcrop_viewfinder46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_gamma44.so proprietary/vendor/lib/libmmcamera_isp_gamma44.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_gic48.so proprietary/vendor/lib/libmmcamera_isp_gic48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_gtm46.so proprietary/vendor/lib/libmmcamera_isp_gtm46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_hdr_be_stats46.so proprietary/vendor/lib/libmmcamera_isp_hdr_be_stats46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_hdr_bhist_stats44.so proprietary/vendor/lib/libmmcamera_isp_hdr_bhist_stats44.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_hdr48.so proprietary/vendor/lib/libmmcamera_isp_hdr48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_ihist_stats46.so proprietary/vendor/lib/libmmcamera_isp_ihist_stats46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_linearization40.so proprietary/vendor/lib/libmmcamera_isp_linearization40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_ltm47.so proprietary/vendor/lib/libmmcamera_isp_ltm47.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so proprietary/vendor/lib/libmmcamera_isp_luma_adaptation40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_mce40.so proprietary/vendor/lib/libmmcamera_isp_mce40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so proprietary/vendor/lib/libmmcamera_isp_mesh_rolloff44.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_pdaf48.so proprietary/vendor/lib/libmmcamera_isp_pdaf48.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_pedestal_correct46.so proprietary/vendor/lib/libmmcamera_isp_pedestal_correct46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_rs_stats46.so proprietary/vendor/lib/libmmcamera_isp_rs_stats46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_scaler_encoder46.so proprietary/vendor/lib/libmmcamera_isp_scaler_encoder46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_scaler_video46.so proprietary/vendor/lib/libmmcamera_isp_scaler_video46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so proprietary/vendor/lib/libmmcamera_isp_scaler_viewfinder46.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_sce40.so proprietary/vendor/lib/libmmcamera_isp_sce40.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_snr47.so proprietary/vendor/lib/libmmcamera_isp_snr47.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_isp_sub_module.so proprietary/vendor/lib/libmmcamera_isp_sub_module.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_llvd.so proprietary/vendor/lib/libmmcamera_llvd.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_optizoom_lib.so proprietary/vendor/lib/libmmcamera_optizoom_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_stillmore_lib.so proprietary/vendor/lib/libmmcamera_stillmore_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_trueportrait_lib.so proprietary/vendor/lib/libmmcamera_trueportrait_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libmmcamera_ubifocus_lib.so proprietary/vendor/lib/libmmcamera_ubifocus_lib.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/liboptizoom.so proprietary/vendor/lib/liboptizoom.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libseemore.so proprietary/vendor/lib/libseemore.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libtrueportrait.so proprietary/vendor/lib/libtrueportrait.so
cp ../../other_repos/alcatraz/vendor_xiaomi_clover/proprietary/vendor/lib/libubifocus.so proprietary/vendor/lib/libubifocus.so

